"""empty message

Revision ID: 033e9666702d
Revises: 1dd5b5cad6a4
Create Date: 2023-10-15 15:49:22.587139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033e9666702d'
down_revision = '1dd5b5cad6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
